amarillos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.sitemaps.views import sitemap
from apps.users.views import login_user
admin.autodiscover()
admin.site.enable_nav_sidebar = False
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    # path('accounts/logout', logout_then_login, name="logout"),
    path(r'', login_user, name='login'),
    path('', include(('apps.users.urls', 'users'), namespace="users")),
    path('', include(('apps.taxes.urls', 'taxes'), namespace="taxes")),
    path('', include(('apps.regions.urls', 'regions'), namespace="regions")),
    path('', include(('apps.vehicles.urls', 'vehicles'), namespace="vehicles")),
    path('', include(('apps.services.urls', 'services'), namespace="services")),
    path('', include(('apps.guests.urls', 'guests'), namespace="guests")),
    #path('sitemap.xml',sitemap,{'sitemaps': sitemaps.sitemaps},name='django.contrib.sitemaps.views.sitemap',),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/services/urls.py
from django.conf.urls import  include
from apps.services.views import *
from django.urls import path
from django.contrib.auth.decorators import login_required

urlpatterns = [
	path(r'pqr',login_required(pqr), name='pqr'),
	path(r'pqr/<int:pk>',login_required(pqr), name='pqr'),
	path(r'pqr_front',login_required(pqr_front), name='pqr_front'),
	path(r'publications',login_required(publications), name='publications'),
	path(r'publications/<int:pk>',login_required(publications), name='publications'),
	path(r'service',login_required(service), name='service'),
 	path(r'travel_history_back',login_required(travel_history_back), name='travel_history_back'),
	path(r'service/<int:pk>',login_required(service), name='service'),
	path(r'service_begin',login_required(service_begin), name='service_begin'),
	path(r'service_front_associate', service_front_associate, name='service_front_associate'),
	path(r'service_front_associate_2/<int:pk>', service_front_associate_2, name='service_front_associate_2'),
	path(r'service_front_associate_3/<int:pk>', service_front_associate_3, name='service_front_associate_3'),
	path(r'service_front_associate_4/<int:pk>', service_front_associate_4, name='service_front_associate_4'),
	path(r'service_front_affiliate', login_required(service_front_affiliate), name='service_front_affiliate'),
	path(r'travel_history',login_required(travel_history), name='travel_history'),

]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import *
from django.utils.crypto import get_random_string
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import timedelta
from apps.states.models import *
from apps.regions.models import *

# Create your models here.
class DocumentType(models.Model):
	name = models.CharField(max_length = 50, null=True)

class Gender(models.Model):
	name = models.CharField(max_length = 50, null=True)

class Blood_Types(models.Model):
	name = models.CharField(max_length = 50, null=True)

class Category(models.Model):
	name = models.CharField(max_length = 50, null=True)
	discount= models.FloatField(default=0)
	
class Extended_User(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='extended_user', primary_key=True)
	document_type = models.ForeignKey(DocumentType,on_delete=models.CASCADE,null=True)
	document_number= models.CharField(max_length = 20, null=True)
	date_birth = models.DateField(null=True)
	photo = models.ImageField(verbose_name='photo',upload_to='users/', null=True)
	gender = models.ForeignKey(Gender, on_delete = models.CASCADE, null=True)
	blood_type = models.ForeignKey(Blood_Types, on_delete = models.CASCADE, null=True)
	category = models.ForeignKey(Category, on_delete = models.CASCADE, null=True)
	cell_phone = models.CharField(max_length = 10, null=True, default="")
	phone_secondary = models.CharField(max_length = 10, null=True)
	city = models.ForeignKey(City, on_delete = models.CASCADE, null=True)
	address = models.CharField(max_length = 100, null=True, default="")
	description_address = models.TextField(null=True, default="")
	favorite_station = models.CharField(max_length = 50, null=True)
	favorite_music = models.CharField(max_length = 50, null=True)
	contact_person_name = models.CharField(max_length = 150, null=True)
	contact_person_phone = models.CharField(max_length = 10, null=True)
	inviting_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='inviting_user')
	authorizing_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='authorizing_user')
	state = models.ForeignKey(State, on_delete = models.CASCADE, default=2)
	call = models.BooleanField(default=False)
	inactive_until = models.DateTimeField(null=True)
	contact_text_check = models.BooleanField(default=False)
	contact_experience_check = models.BooleanField(default=False)
	exchange_data_check = models.BooleanField(default=False)
	def __str__(self):
		return '{}'.format(self.user.first_name+" "+ self.user.last_name)
	def get_code_invitation(self):
		obj_card = Card.objects.filter(user_id=self.pk).first() or None
		if obj_card:
			return obj_card.code
		return None	
	def get_group_name(self):
		list_groups = self.user.groups.all()
		if list_groups:
			return list_groups[0].name
		return None

class Code(models.Model):
	email = models.EmailField()
	name = models.CharField(max_length = 6, unique = True)
	created = models.DateTimeField(auto_now_add=True)
	used = models.BooleanField(default=False)

class TypeSubscription(models.Model):
	name = models.CharField(max_length = 10)
	days = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(365)])
	def __str__(self):
		return self.name
 

class Subscription(models.Model):
	group = models.ForeignKey(Group, on_delete=models.CASCADE)
	type_subscription = models.ForeignKey(TypeSubscription, on_delete=models.CASCADE)
	description = models.TextField(default="")
	price = models.FloatField(default=0, null=True)
	state = models.ForeignKey(State, on_delete = models.CASCADE)
	bonus_direct = models.BigIntegerField(default=0)
	bonus_indirect = models.BigIntegerField(default=0)
	def __str__(self):
		return str(self.group)+" - "+str(self.price)

class Coupon(models.Model):
	code = models.CharField(max_length=50)
	state = models.ForeignKey(State, on_delete = models.CASCADE)
	subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
	used = models.BooleanField(default=False)
	create_date = models.DateTimeField(blank=True,null=True, default=timezone.now)
	first_name = models.CharField(max_length = 100)
	last_name = models.CharField(max_length = 100)
	cell_phone = models.CharField(max_length = 10, null=True, default="")
	email = models.EmailField(null=True, default="")
	city = models.ForeignKey(City, on_delete = models.CASCADE)
	expiration_date = models.DateTimeField(blank=True,null=True, default=timezone.now)
	def get_group_name(self):
		list_groups = self.subscription.groups.all()
		if list_groups:
			return list_groups[0].name
		return None
	def get_activation_date(self):
		obj_invoice =  Invoice.objects.filter(coupon=self).first() or None
		if obj_invoice:
				return obj_invoice.create_date
		return None
	def get_used(self):
		if 	self.used:
			return "Si"
		return "No"
	
class Invoice(models.Model):
    state = models.ForeignKey(InvoiceState, on_delete=models.CASCADE, null= True)
    create_date = models.DateTimeField(null=True, default=timezone.now)
    total_price = models.FloatField(default=0, null=True)
    payment_method = models.CharField(max_length=30, null=True)
    id_transaction = models.CharField(max_length=30, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE, null= True)
    payment_reference = models.CharField(null=True, max_length=50, unique= True)
    user = models.ForeignKey(Extended_User, on_delete=models.CASCADE, null=True)

class ValidationCard(models.Model):
	name = models.CharField(max_length = 10, unique=True, null=True, default="")

class Card(models.Model):
	user = models.ForeignKey(Extended_User, on_delete=models.CASCADE, null=True)
	code = models.CharField(max_length = 10, unique=True)
	activation_code = models.CharField(max_length = 10, null=True)
	validation_card = models.ForeignKey(ValidationCard, on_delete=models.CASCADE, null=True)
	def payment_method(self):
		obj_card_subscription = CardSubscription.objects.filter(card=self).first() or None
		if obj_card_subscription:
			return obj_card_subscription.invoice.payment_method
		return ""
	def fecha_vencimiento(self):
		obj_card_subscription = CardSubscription.objects.filter(card=self).first() or None
		if obj_card_subscription:
			return obj_card_subscription.fecha_vencimiento()
		return ""
	def fecha_pago(self):
		obj_card_subscription = CardSubscription.objects.filter(card=self).first() or None
		if obj_card_subscription:
			return obj_card_subscription.payday
		return ""

class CardSubscription(models.Model):
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, null=True)
	subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
	card = models.ForeignKey(Card, on_delete=models.CASCADE)
	payday = models.DateField(default=timezone.now)
	state = models.ForeignKey(State, on_delete = models.CASCADE)
	def fecha_vencimiento(self):
		return self.payday + timedelta(days=self.subscription.type_subscription.days)
 
class AllyCategory(models.Model):
    name = models.CharField(max_length = 200)
    create_date = models.DateTimeField(null=True, default=timezone.now)
    create_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='AllyCategory_create_user')
    def __str__(self):
        return self.name
    
class Ally(models.Model):
	photo_local_1 = models.ImageField(verbose_name='photo_local_1',upload_to='ally/')
	photo_local_2 = models.ImageField(verbose_name='photo_local_2',upload_to='ally/',null=True,blank=True)
	photo_local_3 = models.ImageField(verbose_name='photo_local_3',upload_to='ally/',null=True,blank=True)
	name = models.CharField(max_length = 200)
	description = models.TextField(null=False)
	number_mercantil = models.CharField(max_length = 100)
	category = models.ForeignKey(AllyCategory,on_delete = models.CASCADE)
	cell_phone = models.CharField(max_length = 10, null=True, default="")
	city = models.ForeignKey(City, on_delete = models.CASCADE, null=True)
	address = models.CharField(max_length = 100, null=True, default="")
	user = models.ForeignKey(Extended_User, on_delete=models.CASCADE, null=True, related_name='Ally_user')
	inactive_until = models.DateTimeField(null=True,blank=True)
	state = models.ForeignKey(State, on_delete = models.CASCADE)
	description_state = models.TextField(null=False,blank=True)
	create_user = models.ForeignKey(Extended_User, on_delete=models.CASCADE, null=True, related_name='Ally_create_user')
	create_date = models.DateTimeField(null=True, default=timezone.now)
	modification_user = models.ForeignKey(Extended_User, on_delete=models.CASCADE, null=True, related_name='Ally_modification_user')
	modification_date = models.DateTimeField(null=True, default=timezone.now)
	def __str__(self):
		return self.name

# class PromotionsByCategory(models.Model):
# 	category = models.ForeignKey(Category, on_delete = models.CASCADE)
# 	date_start = models.DateTimeField(null=True)
# 	date_end = models.DateTimeField(null=True)

apps/services/forms.py
from django import forms
from apps.services.models import *
from django.forms import ModelForm, ImageField
from django.core.files.images import get_image_dimensions

class PqrForm(forms.ModelForm):
    class Meta:
        model=Pqr
        fields='__all__'
    def __init__(self, *args, **kwargs): 
        super(PqrForm, self).__init__(*args, **kwargs)
        if len(args)>0:
            context=args[0].dict()
            if context.get("route") == "pqr_edit":
                del self.fields['service']
                del self.fields['type_pqr']
                del self.fields['user_question']

            elif context.get("route") == "service_edit":
                del self.fields['service']
                del self.fields['type_pqr']
                del self.fields['user_question']

            elif context.get("route") == "pqr_front_create":
                del self.fields['service']
                del self.fields['user_answer']

class PqrForm2(forms.ModelForm):
    class Meta:
        model = Pqr
        fields = '__all__'

    def __init__(self, *args, **kwargs):
       super(PqrForm2, self).__init__(*args, **kwargs)
       self.fields['service'].required=False
       self.fields['user_question'].required=False
       self.fields['user_answer'].required=False

class PqrFormOperator(forms.ModelForm):
    class Meta:
        model=Pqr
        fields=['state', 'modification_date']

class ServiceForm(forms.ModelForm):
    code_verify = forms.CharField(required=False)
    action = forms.CharField(required=False)
    route = forms.CharField(required=False)
    image = ImageField(required=False)
    class Meta:
        model=Service
        fields='__all__'
    def __init__(self, *args, **kwargs): 
        super(ServiceForm, self).__init__(*args, **kwargs) 
        if len(args)>0:
            context=args[0].dict()
            del self.fields['creation_date']
            del self.fields['promotion_category']
            del self.fields['promotion_category_percent']
            del self.fields['initial_affectation']
            del self.fields['initial_affectation_percent']
            del self.fields['discount_increase_policies']
            del self.fields['discount_increase_policies_percent']
            del self.fields['total']
            del self.fields['vehicle']
            if context.get("route") == "service_front_associate_3":
                del self.fields['user_receiving']
                del self.fields['location']
                del self.fields['code']
                del self.fields['state']
                del self.fields['time_start']
                del self.fields['time_stop']
                del self.fields['flag_call']
                del self.fields['score']
            if context.get("route") == "service_front_associate_3_delete":
                del self.fields['user_receiving']
                del self.fields['location']
                del self.fields['code']
                del self.fields['time_start']
                del self.fields['time_stop']
                del self.fields['flag_call']
                del self.fields['score']
                del self.fields['payment_method']
            elif context.get("route") == "service_front_affiliate":
                del self.fields['user_providing'] 
                del self.fields['time_start'] 
                del self.fields['time_stop']
                del self.fields['price']
                del self.fields['flag_call']
                del self.fields['score']
                del self.fields['payment_method']
            elif context.get("route") == "service":
                del self.fields['user_receiving']
                del self.fields['user_providing']
                del self.fields['price']
                del self.fields['location']
                del self.fields['code']
                del self.fields['state']
                del self.fields['time_start']
                del self.fields['time_stop']
                del self.fields['payment_method']

    def clean(self):
        cleaned_data = super().clean()
        price = self.cleaned_data.get("price")
        action = self.cleaned_data.get("action")
        if price and not (action == "delete" and price == 0):
            validation_rate=Rate.objects.filter(value=price)
            if not validation_rate.exists():
                self.add_error('price', 'Valor no valido, ingrese otro valor')

class ServiceCollectionForm(forms.ModelForm):
    class Meta:
        model=ServiceCollection
        fields='__all__'
    def __init__(self, *args, **kwargs): 
        super(ServiceCollectionForm, self).__init__(*args, **kwargs)
        del self.fields['total_price']

class PublicationForm(forms.ModelForm):
    class Meta:
        model=Publication
        fields='__all__'

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            w, h = get_image_dimensions(photo)
            if w != 500 or h != 500:
                raise forms.ValidationError ("Subir una imagen de 500*500 pixeles")
        return photo

templates/services/service.html
{% extends "general/base.html" %}
{% block menu %}{% include "general/service_menu.html" %}{% endblock%}
{% load humanize %}
{% block script %}
<script>
$('#GeneralModal').modal('{{modal}}');
$('#GeneralModal').on('hidden.bs.modal', function (e) {
  window.location.replace("/service");
});
</script> 
{% endblock %}
{% block container %}
<form id="form_search" class="row mt-2" method="get">
  <div class="col-4">
    <div class="form-group">
      <input type="text" class="form-control" type="text" name="bar_search" value="" placeholder="cod. invitación, teléfono, cedula">
    </div>
  </div>
  <div class="col-3">
    <div class="form-group">
      <select class="form-control" id="filter_state" name="filter_state">
        <option value="">Estados(opcional)</option>
        {% for x in states_service %}
          <option value="{{x.id}}">{{x.name}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="col-3">
    <div class="form-group">
      <select class="form-control" id="city_search" name="city_search">
        <option value="">Ciudad(opcional)</option>
        {% for x in cities %}
          <option value="{{x.id}}">{{x.name}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="col-2">
    <a href="#"><button type="submit"  class="btn bg-primary btn-block text-truncate text-white"><i class="fa fa-search"></i> Buscar</button></a>
  </div>
</form>
{% if request.user.groups.all.0.id == 2 %}
<div class="row mt-2 d-flex justify-content-end">
  <a class="h6 text-success font-weight-bold" href="{% url 'services:service_begin' %}"><i class="fa fa-plus mr-2"></i>Nuevo</a>
</div>
{% endif %}
<div class="row table-responsive" style="height: 100%;">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="min-80" scope="col">N sevicio contrato</th>
        <th class="min-80" scope="col">PQR solicitado</th>
        <th class="min-80" scope="col">Estado</th>
        <th class="min-80" scope="col">Fecha finalizado</th>
        <th class="min-80" scope="col">Ciudad y dirección de destino</th>
        <th class="min-80" scope="col">Nombre dirección</th>
        <th class="min-80" scope="col">Tarjeta y categoria</th>
        <th class="min-80" scope="col">Información pasajero</th>
        <th class="min-80" scope="col">llamado al Usuario</th>
        <th class="min-80" scope="col">Información conductor</th>
        <th class="min-80" scope="col">Llamado al conductor</th>
        <th class="min-80" scope="col">Nombre usuario contáctado</th>
        <th class="min-80" scope="col">Usuario ubicado</th>
        <th class="min-80" scope="col">Servicio calificado</th>
        <th class="min-80" scope="col">Placa</th>
        <th class="min-80" scope="col">Servicio tarificado</th>
        <th class="min-80" scope="col">Precio sugerido</th>
        <th class="min-80" scope="col">Metodo de pago</th>
        <th class="min-80" scope="col">Código servicio creado</th>
        <th class="min-80" scope="col">N código de servicio</th>
        <th class="min-80" scope="col">Beneficiado por categoria</th>
        <th class="min-80" scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for x  in services %}
      <tr>
        <th scope="row">{{x.id}}</th>
        <td>{{x.pqr_records.0.type_pqr.name}}</td>
        <td>{{x.state.name }}</td>
        <td>{{x.time_stop |date:"Y-m-d H:i:s"}}</td>
        <td>{{x.location.city.name}} / {{x.location.address}} </td>
        <td>{{x.location.name}}</td>
        <td>{{x.user_receiving.get_group_name}}/{{x.user_receiving.category.name}}</td>
        <td>
          <button class="btn btn-sm btn-info" onclick="sw_mensaje('<b>Nombre:</b> {{x.user_receiving.user.get_full_name}}<br><b>Telefono 1:</b> {{x.user_receiving.cell_phone}}<br><b>Telefono 2:</b> {{x.user_receiving.phone_secondary}}<br><b>Codigo:</b> {{x.cod_receiving}}{% if request.user.groups.all.0.id == 4 %}<br><b>Documento:</b> {{x.user_receiving.document_number}}{% endif %}','Información pasajero')" ><i class="fa fa-info-circle"></i></button>   
        </td>
        <td>PENDIENTE</td>
        <td>
          <button class="btn btn-sm btn-info" onclick="sw_mensaje('<b>Nombre:</b> {{x.user_providing.user.get_full_name}}<br> <b>Telefono 1:</b> {{x.user_providing.cell_phone}}<br> <b>Telefono 2:</b> {{x.user_providing.phone_secondary}}<br> <b>Codigo:</b> {{x.cod_providing}} {% if request.user.groups.all.0.id == 4 %}<br> <b>Documento:</b> {{x.user_providing.document_number}} {% endif %}','Información conductor')"> <i class="fa fa-info-circle"></i> </button> 
        </td>
        <td>PENDIENTE</td>
        <td>{{x.pqr_records.0.user_question.user.get_full_name}}</td>
        <td>{{x.flag_call |default_if_none:0|intcomma}}</td>
        <td>{{x.score |default_if_none:0|intcomma}}</td>
        <td>{{x.vehicle.plate}}</td>
        <td>${{x.price|default_if_none:0|intcomma}}</td>
        <td>${{x.total|default_if_none:0|intcomma}}</td>
        <td>{{x.payment_method.name}}</td>
        <td>{{x.creation_date |date:"Y-m-d H:i:s"}}</td>
        <td>{{x.code}}</td>
        <td>-{{x.user_receiving.category.discount}}%</td>
        <td class="px-2 py-3" scope="col">
            <a class="fa fa-pencil-square-o cursor-pointer" href="{% url 'services:service' x.id %}"></a>
        </td>



      </tr>
      {% endfor %}
    </tbody>
  </table>  
</div>
<div class="row">
  <div class="col-12">
    <nav>
      <ul class="pagination justify-content-center">
        {% if services.has_previous %}
        <li class="page-item"><a  class="page-link" href="?page=1"><i class="fa fa-fast-backward"></i></a></li>
        {% endif %}
        {% if services.has_previous %}
        <li class="page-item"><a  class="page-link" href="?page={{ services.previous_page_number }}"><i class="fa fa-step-backward"></i></a></li>
        {% endif %}
        {% for i in services.paginator.page_range %}
          {% if services.number == i %}
          <li class="page-item active"><a  class="page-link" href="" disabled>{{ i }}</a></li>
          {% else %}
          <li class="page-item"><a  class="page-link" href="?page={{ i }}" >{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if services.has_next%}
        <li class="page-item"><a  class="page-link" href="?page={{ services.next_page_number }}"><i class="fa fa-step-forward"></i></a></li>
        {% endif %}
        {% if services.has_next %}
        <li class="page-item"><a  class="page-link" href="?page={{ services.paginator.num_pages }}"><i class="fa fa-fast-forward"></i></a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
{% endblock %}
{% block modal_title %}Crear {{name}}{% endblock%}
{% block modal_body %}
<form  method="POST" class="form-signin m-2" id="createform">
  {% csrf_token %}
  {% if not pqr %}
  <div class="form-group row">
    <label for="user_question" class="col-3 col-form-label text-right">
      A quien contactamos:
    </label>
    <div class="col-9">
      <select class="form-control {% if form.user_question.errors %}border-bottom border-danger{% endif %}" id="user_question" name="user_question">
        <option>Selecciona una opción</option>
        {% if service.user_receiving.user.get_full_name %}
        <option value="{{service.user_receiving.user.id}}" {% if form.errors or form_service.errors %}{% if form.user_question.value|floatformat:'0' == service.user_receiving.user.id|floatformat:'0' %} selected {% endif %}{% endif %}>{{service.user_receiving.user.get_full_name}}(pasajero)</option>
        {% endif %}
        {% if service.user_providing.user.get_full_name %}
        <option value="{{service.user_providing.user.id}}" {% if form.errors or form_service.errors %}{% if form.user_question.value|floatformat:'0' == service.user_providing.user.id|floatformat:'0' %} selected {% endif %}{% endif %}>{{service.user_providing.user.get_full_name}}(conductor)</option>
        {% endif %}
      </select>
    </div>
    {{form.user_question.errors}}
  </div>
  <div class="form-group row">
    <label for="flag_call" class="col-3 col-form-label text-right">
      Contesto:
    </label>
    <div class="col-9">
      <select class="form-control {% if form_service.flag_call.errors %}border-bottom border-danger{% endif %}" id="flag_call" name="flag_call">
        <option value="">Selecciona una opción</option>
        <option value="SI" {% if form.errors or form_service.errors %}{% if form_service.flag_call.value == 'SI' %} selected {% endif %}{% endif %}>SI</option>
        <option value="NO" {% if form.errors or form_service.errors %}{% if form_service.flag_call.value == 'NO' %} selected {% endif %}{% endif %}>NO</option>
      </select>
    </div>
    {{form_service.flag_call.errors}}
  </div>
  <div class="form-group row">
    <label for="type_pqr" class="col-3 col-form-label text-right">
      Tipo de pqr:
    </label>
    <div class="col-9">
      <select class="form-control {% if form.type_pqr.errors %}border-bottom border-danger{% endif %}" id="type_pqr" name="type_pqr">
        <option>Selecciona una opción</option>
        {% for x in type_pqrs %}
          <option value="{{x.id}}" {% if form.errors or form_service.errors %}{% if form.type_pqr.value|floatformat:'0' == x.id|floatformat:'0' %} selected {% endif %}{% endif %}>{{x.name}}</option>
        {% endfor %}
      </select>
    </div>
    {{form.type_pqr.errors}}
  </div>
  {% else %}
  <div class="row mb-3">
    <div class="col-8">
      <div class="row m-0">
        <div class="col-6 font-weight-bold">
          A quien contactamos:
        </div>
        <div class="col-6">
          {{pqr.user_question.user.get_full_name}}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row m-0">
        <div class="col-6 font-weight-bold">
          Contesto:
        </div>
        <div class="col-6">
          {{service.flag_call}}
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="row m-0">
        <div class="col-6 font-weight-bold">
          Tipo PQR:
        </div>
        <div class="col-6">
          {{pqr.type_pqr.name}}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row m-0">
        <div class="col-6 font-weight-bold">
          Calificación:
        </div>
        <div class="col-6">
          {{service.score}}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="form-group row">
    <label for="discount" class="col-3 col-form-label text-right">
      Descripción:
    </label>
    <div class="col-9">
      <textarea class="form-control {% if form.description.errors %}border-bottom border-danger{% endif %}" name="description" id="description" placeholder="Mensaje">{% if form.errors or form_service.errors %}{{form.description.value}}{% else %}{{pqr.description}}{% endif %}</textarea>
    </div>
    {{form.description.errors}}
  </div>
  <div class="form-group row">
    <label for="state" class="col-3 col-form-label text-right">
      Estado:
    </label>
    <div class="col-9">
      <select class="form-control {% if form.state.errors %}border-bottom border-danger{% endif %}" id="state" name="state">
        <option>Selecciona una opción</option>
        {% for x in states %}
          <option value="{{x.id}}" {% if form.errors or form_service.errors %}{% if form.state.value|floatformat:'0' == x.id|floatformat:'0' %}selected{% endif %}{% elif x.id|floatformat:'0' == pqr.state.id|floatformat:'0'%}selected{% endif %}>{{x.name}}</option>
        {% endfor %}
      </select>
    </div>
    {{form.state.errors}}
  </div>
  {% if not pqr %}
  <div class="form-group row">
    <label for="score" class="col-3 col-form-label text-right">
      Calificación:
    </label>
    <div class="col-9">
      <select class="form-control {% if form_service.score.errors %}border-bottom border-danger{% endif %}" id="score" name="score">
        <option>Selecciona una opción</option>
        {% for i in '12345'|make_list %}
          <option value="{{forloop.counter}}" {% if form.errors or form_service.errors %} {% if form_service.score.value|floatformat:'0' == forloop.counter|floatformat:'0' %} selected {% endif %}{% endif %}>{{forloop.counter}}</option>
        {% endfor %}
      </select>
    </div>
    {{form_service.score.errors}}
  </div>
  {% endif %}
</form>
{% endblock%}
{% block modal_footer %}
<button type="button" class="btn btn-sm mt-1 btn-secondary btn-block" data-dismiss="modal">Cerrar</button>
<button type="submit" form="createform" name="action" value="create" class="btn btn-sm btn-block btn-primary">
  {% if city %}Editar {% else %}Crear{% endif %}
</button>
{% endblock%}