amarillos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.sitemaps.views import sitemap
from apps.users.views import login_user
admin.autodiscover()
admin.site.enable_nav_sidebar = False
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    # path('accounts/logout', logout_then_login, name="logout"),
    path(r'', login_user, name='login'),
    path('', include(('apps.users.urls', 'users'), namespace="users")),
    path('', include(('apps.taxes.urls', 'taxes'), namespace="taxes")),
    path('', include(('apps.regions.urls', 'regions'), namespace="regions")),
    path('', include(('apps.vehicles.urls', 'vehicles'), namespace="vehicles")),
    path('', include(('apps.services.urls', 'services'), namespace="services")),
    path('', include(('apps.guests.urls', 'guests'), namespace="guests")),
    #path('sitemap.xml',sitemap,{'sitemaps': sitemaps.sitemaps},name='django.contrib.sitemaps.views.sitemap',),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/guests/urls.py
from django.urls import path
from .views import *

app_name = "guests"

urlpatterns = [
    path('transfer',TransferView.as_view(),name='transfer'),
    path('recharge',RechargeView.as_view(),name='recharge'),
    path('balance',BalanceList.as_view(),name='balance'),
    path('bonus',BonusesList.as_view(),name='balance_bonus'),
] 

apps/guests/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

from apps.users.models import CardSubscription, Extended_User

class wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='wallet_user', primary_key=True)
    balance = models.BigIntegerField(default=0)
    class Meta:
        db_table = "wallet"
        verbose_name_plural = "Wallet"
        ordering = ["user"]
    
    def __str__(self):
        return str(self.user)
    
class types_movements(models.Model):
    name = models.CharField(max_length=200)
    class Meta:
        db_table = "types_movements"
        verbose_name_plural = "Types movements"
        ordering = ["name"]
    
    def __str__(self):
        return str(self.name)
    
class balance_wallet(models.Model):
    CHOICES_TYPE_BONUS = [
        ("1","Directo"),
        ("2","Indirecto"),
    ]
    type_movement = models.ForeignKey(types_movements,on_delete=models.RESTRICT,related_name='balance_type_movements')
    amount = models.BigIntegerField()
    wallet = models.ForeignKey(wallet,on_delete=models.RESTRICT,related_name='wallet_balance')
    payment_method = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=200, null=True)
    transaction_number = models.CharField(max_length=100, null=True)
    user_bonus_origin = models.ForeignKey(Extended_User,on_delete=models.RESTRICT,related_name='balance_wallet_user_bonus',null=True)
    type_bonus = models.CharField(max_length=1,choices=CHOICES_TYPE_BONUS)
    card_subscription = models.ForeignKey(CardSubscription,on_delete=models.RESTRICT,related_name='balance_wallet_card_suscription',null=True)
    create_date = models.DateTimeField(null=True, default=timezone.now)
    create_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='balance_wallet_create_user')    
    transfer_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='balance_wallet_transfer_user')    
    origin_user = models.ForeignKey(User, on_delete = models.CASCADE, null=True, related_name='balance_wallet_origin_user')    
    class Meta:
        db_table = "balance_wallet"
        verbose_name_plural = "Balance wallet"
        ordering = ["-create_date"]
        indexes = [
            models.Index(fields=['wallet']),
            models.Index(fields=['type_movement']),
            models.Index(fields=['wallet','user_bonus_origin']),
        ]  
    
    def __str__(self):
        return str(self.create_date)+" | "+str(self.type_movement)+"-"+str(self.amount)
    
    def code_invitation_transfer_user(self):
        code = ""
        if self.transfer_user:
            obj_user = Extended_User.objects.filter(user=self.transfer_user).first() or None
            if obj_user:
                code = obj_user.get_code_invitation()+" | "+obj_user.user.first_name+" "+obj_user.user.last_name
        return code
    
    def code_invitation_origin_user(self):
        code = ""
        if self.origin_user:
            obj_user = Extended_User.objects.filter(user=self.origin_user).first() or None
            if obj_user:
                code = obj_user.get_code_invitation()+" | "+obj_user.user.first_name+" "+obj_user.user.last_name
        return code
    
    def code_invitation_direct(self):
        code = ""
        if self.user_bonus_origin:
            obj_user_invitation = self.user_bonus_origin
            if obj_user_invitation:
                code = str(obj_user_invitation.get_code_invitation())+" | "+obj_user_invitation.user.first_name+" "+obj_user_invitation.user.last_name
        return code

apps/guests/forms.py
from django import forms
from apps.guests.models import balance_wallet, wallet
from apps.users.models import Card

class FormBalance(forms.Form):
    codigo_invitacion = forms.CharField(
		label="Código usuario",  
        required=True, 
        widget=forms.TextInput(attrs={ 
            'class' :'form-control', 
            'placeholder' :'Codigo de usuario', 
        }) 
	)
    def clean(self):
        cleaned_data = super(FormBalance, self).clean()
        codigo_invitacion = cleaned_data.get("codigo_invitacion")
        if codigo_invitacion:
            if not Card.objects.filter(code=codigo_invitacion).exists():
                self.add_error('codigo_invitacion','El código indicado no existe')

class FormCreateRecharge(forms.ModelForm):
   
    invitation_code = forms.CharField(
		label="Código usuario",  
        required=True, 
        widget=forms.TextInput(attrs={ 
            'class' :'form-control', 
        }) 
	)
   
    class Meta:       
        model = balance_wallet
        fields = ('amount',)
        labels = {
            'amount':('Valor recarga'),
        }       
        widgets = {
            'amount': forms.NumberInput(
                attrs={
                    'min':0,
                    'max':10,
                    'autocomplete': 'off',
                    'class': 'form-control',                    
                }
            ),
        }
        error_messages = {
            "amount": {
                "required" : ("Debe de indicar un valor de recarga"),
            },
        } 

    def clean(self):
        cleaned_data = super(FormCreateRecharge, self).clean()
        amount = cleaned_data.get("amount")               
        invitation_code = cleaned_data.get("invitation_code")
        if amount < 1:
            self.add_error('amount','Debe de indicar un numero mayor a 0')
        if invitation_code:
            if not Card.objects.filter(code=invitation_code).exists():
                self.add_error('invitation_code','El código indicado no existe')
                
class FormCreateTransfer(forms.ModelForm):
   
    invitation_code_origin = forms.CharField(
		label="Código usuario origen",  
        required=True, 
        widget=forms.TextInput(attrs={ 
            'class' :'form-control', 
        }) 
	)
    invitation_code_destination = forms.CharField(
		label="Código usuario destino",  
        required=True, 
        widget=forms.TextInput(attrs={ 
            'class' :'form-control', 
        }) 
	)
   
    class Meta:       
        model = balance_wallet
        fields = ('amount',)
        labels = {
            'amount':('Valor recarga'),
        }       
        widgets = {
            'amount': forms.NumberInput(
                attrs={
                    'min':0,
                    'max':10,
                    'autocomplete': 'off',
                    'class': 'form-control',                    
                }
            ),
        }
        error_messages = {
            "amount": {
                "required" : ("Debe de indicar un valor de recarga"),
            },
        } 

    def clean(self):
        cleaned_data = super(FormCreateTransfer, self).clean()
        amount = cleaned_data.get("amount")               
        invitation_code_origin = cleaned_data.get("invitation_code_origin")
        invitation_code_destination = cleaned_data.get("invitation_code_invitation_code_destination")
        if amount < 1:
            self.add_error('amount','Debe de indicar un numero mayor a 0')
        if invitation_code_origin:
            if not Card.objects.filter(code=invitation_code_origin).exists():
                self.add_error('invitation_code_origin','El código indicado de origen no existe')
            else:
                obj_card = Card.objects.filter(code=invitation_code_origin).first()
                obj_extended_user = obj_card.user
        if invitation_code_destination:
            if not Card.objects.filter(code=invitation_code_destination).exists():
                self.add_error('invitation_code_destination','El código indicado de destino no existe')        
        wallet_origin = wallet.objects.filter(user=obj_extended_user.user).first() or None
        if wallet_origin:
            if wallet_origin.balance < amount:
                self.add_error('amount','La cantidad indicada supera el saldo del usuario')        
        else:
            self.add_error('invitation_code_origin','El código indicado no posee una wallet')        
        

apps/guests/views.py
# APPS DJANGO
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView,View 
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.core.paginator import  InvalidPage
# APPS PROPIA
from apps.guests.forms import FormBalance, FormCreateRecharge,FormCreateTransfer
from apps.guests.models import balance_wallet, wallet
from apps.users.models import Card

TEMPLATE_ROOT = "guests/"

class BalanceList(View):
    def get(self,request):
        context = {}
        context["active_balance"] = "text-dark"
        context["form_busqueda"] = FormBalance()
        codigo_invitacion = request.GET.get("codigo_invitacion") or None
        if codigo_invitacion:
            context["codigo_invitacion"] = codigo_invitacion
            formulario = FormBalance(request.GET)
            if formulario.is_valid():
                obj_card = Card.objects.filter(code=codigo_invitacion).first()
                obj_extended_user = obj_card.user
                obj_user = obj_extended_user.user
                obj_user_wallet = wallet.objects.get(user=obj_user)
                movements = obj_user_wallet.wallet_balance.all()
                total_movements = 0
                for movement in movements:
                    total_movements += movement.amount
                context["total_movements"] = total_movements
                page = request.GET.get('page', 1)
                paginator = Paginator(movements,20)
                try:
                    movements = paginator.page(page)
                except PageNotAnInteger:
                    movements = paginator.page(1)
                except EmptyPage:
                    movements = paginator.page(paginator.num_pages)
                context["movements"] = movements
            context["form_busqueda"] = formulario
        return render(request, TEMPLATE_ROOT+'balance.html', context)

class BonusesList(View):
    def get(self,request):
        context = {}
        context["active_bonus"] = "text-dark"
        context["form_busqueda"] = FormBalance()
        codigo_invitacion = request.GET.get("codigo_invitacion") or None
        if codigo_invitacion:
            context["codigo_invitacion"] = codigo_invitacion
            formulario = FormBalance(request.GET)
            if formulario.is_valid():
                obj_card = Card.objects.filter(code=codigo_invitacion).first()
                obj_extended_user = obj_card.user
                obj_user = obj_extended_user.user
                obj_user_wallet = wallet.objects.get(user=obj_user)
                movements = obj_user_wallet.wallet_balance.all().filter(type_movement__id__in = ["4","5"])
                total_movements = 0
                for movement in movements:
                    total_movements += movement.amount
                context["total_movements"] = total_movements
                page = request.GET.get('page', 1)
                paginator = Paginator(movements,20)
                try:
                    movements = paginator.page(page)
                except PageNotAnInteger:
                    movements = paginator.page(1)
                except EmptyPage:
                    movements = paginator.page(paginator.num_pages)
                context["movements"] = movements
            context["form_busqueda"] = formulario
        return render(request, TEMPLATE_ROOT+'balance_bonus.html', context)
    

class RechargeView(CreateView):
    form_class = FormCreateRecharge
    success_url = reverse_lazy("guests:recharge")
    template_name= TEMPLATE_ROOT+'formulario.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_recharge"] = "text-dark"
        return context

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(errors_form=[form]))
    
    def form_valid(self, form):
        obj_movimiento = form.save(commit=False)
        invitation_code = form.cleaned_data.get("invitation_code")
        if invitation_code:
            obj_card = Card.objects.filter(code=invitation_code).first()
            obj_extended_user = obj_card.user
            obj_user = obj_extended_user.user
            obj_user_wallet = wallet.objects.get(user=obj_user)
        obj_movimiento.type_movement_id = 1
        obj_movimiento.wallet = obj_user_wallet
        obj_movimiento.create_user = self.request.user
        obj_movimiento.save()
        obj_user_wallet.balance += obj_movimiento.amount
        obj_user_wallet.save()
        messages.add_message(self.request, messages.SUCCESS, "Recarga creada correctamente")
        return HttpResponseRedirect(self.success_url)

class TransferView(CreateView):
    form_class = FormCreateTransfer
    success_url = reverse_lazy("guests:transfer")
    template_name= TEMPLATE_ROOT+'formulario_transfer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_transfer"] = "text-dark"
        return context

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(errors_form=[form]))
    
    def form_valid(self, form):
        obj_movimiento = form.save(commit=False)
        invitation_code_origin = form.cleaned_data.get("invitation_code_origin")
        invitation_code_destination = form.cleaned_data.get("invitation_code_destination")
        if invitation_code_origin:
            obj_card = Card.objects.filter(code=invitation_code_origin).first()
            obj_extended_user = obj_card.user
            obj_user = obj_extended_user.user
            obj_user_wallet_origin = wallet.objects.get(user=obj_user)
        if invitation_code_destination:
            obj_card = Card.objects.filter(code=invitation_code_destination).first()
            obj_extended_user = obj_card.user
            obj_user = obj_extended_user.user
            obj_user_wallet_destination = wallet.objects.get(user=obj_user)
        obj_movimiento.type_movement_id = 2
        obj_movimiento.wallet = obj_user_wallet_origin
        obj_movimiento.create_user = self.request.user
        obj_movimiento.transfer_user = obj_user_wallet_destination.user
        obj_movimiento.amount = obj_movimiento.amount * -1
        obj_movimiento.save()
        obj_user_wallet_origin.balance += obj_movimiento.amount
        obj_user_wallet_origin.save()
        obj_movimiento_discount = balance_wallet()
        obj_movimiento_discount.type_movement_id = 3
        obj_movimiento_discount.wallet = obj_user_wallet_destination
        obj_movimiento_discount.create_user = self.request.user
        obj_movimiento_discount.origin_user = obj_user_wallet_origin.user
        obj_movimiento_discount.amount = obj_movimiento.amount * -1
        obj_movimiento_discount.save()
        obj_user_wallet_destination.balance += obj_movimiento_discount.amount
        obj_user_wallet_destination.save()
        messages.add_message(self.request, messages.SUCCESS, "Transferencia realizada correctamente")
        return HttpResponseRedirect(self.success_url)

templates/guests/balance.html
{% extends 'general/base.html' %}
{% load humanize %}
{% block menu %}{% include "general/guest_menu.html" %}{% endblock%}
{% load static %}
{% block script %}
{% endblock %}
{% block container %}
<form id="form_search" class="row mt-2" method="get">
	<div class="col-6">
        <div class="form-group">
            {{ form_busqueda.codigo_invitacion }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form_busqueda.codigo_invitacion.errors}}</div>
    </div>
	<div class="col-6">
		<button type="submit" form="form_search" name="action" value="create" class="btn btn-sm btn-block btn-primary"><i class="fa fa-search"></i> Buscar</button>
    </div>
</form>

{% if movements %}
	<div class="row table-responsive" style="height: 500px;">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class="min-80"  scope="col">Fecha</th>
					<th class="min-100 text-left" scope="col">Tipo de movimiento</th>
					<th class="min-80 text-right"  scope="col">Valor</th>
					<th class="min-100 text-left" scope="col">Origen / Destino</th>
				</tr>
			</thead>
			<tbody>
				{% for movement in movements %}
				<tr>
					<td scope="row">{{movement.create_date|date:"Y-m-d H:i:s"}}</td>
					<td scope="row" class="text-left">{{movement.type_movement}}</td>
					{% if  movement.amount < 0 %}
						<td scope="row" class="text-right text-danger">${{movement.amount|intcomma}}</td>
					{% else %}
						<td scope="row" class="text-right">${{movement.amount|intcomma}}</td>
					{% endif %}
					{% if movement.type_movement.id == 2 %}
						<td scope="row" class="text-left">Destino: {{movement.code_invitation_transfer_user}}</td>
					{% elif  movement.type_movement.id == 3 %}					
						<td scope="row" class="text-left">Origen: {{movement.code_invitation_origin_user}}</td>
					{% else %}
						<td scope="row" class="text-left"></td>
					{% endif %}
				</tr>		
				{% endfor %}
			</tbody>
			<thead>
				<tr>
					<th colspan="3" class="text-right">Total</th>
					<th class="text-right">$ {{total_movements|intcomma}}</th>
				</tr>
			</thead>	
		</table>
	</div>
	<div class="row">
		<div class="col-12">
		<nav>
			<ul class="pagination justify-content-center">
			{% if movements.has_previous %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page=1"><i class="fa fa-fast-backward"></i></a></li>
			{% endif %}
			{% if movements.has_previous %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.previous_page_number }}"><i class="fa fa-step-backward"></i></a></li>
			{% endif %}
			{% for i in movements.paginator.page_range %}
				{% if movements.number == i %}
				<li class="page-item active"><a  class="page-link" href="" disabled>{{ i }}</a></li>
				{% else %}
				<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ i }}" >{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if movements.has_next%}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.next_page_number }}"><i class="fa fa-step-forward"></i></a></li>
			{% endif %}
			{% if movements.has_next %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.paginator.num_pages }}"><i class="fa fa-fast-forward"></i></a></li>
			{% endif %}
			</ul>
		</nav>
		</div>
	</div>
{% endif %}
  {% endblock %}

templates/guests/balance_bonus.html
{% extends 'general/base.html' %}
{% load humanize %}
{% block menu %}{% include "general/guest_menu.html" %}{% endblock%}
{% load static %}
{% block script %}
{% endblock %}
{% block container %}
<form id="form_search" class="row mt-2" method="get">
	<div class="col-6">
        <div class="form-group">
            {{ form_busqueda.codigo_invitacion }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form_busqueda.codigo_invitacion.errors}}</div>
    </div>
	<div class="col-6">
		<button type="submit" form="form_search" name="action" value="create" class="btn btn-sm btn-block btn-primary"><i class="fa fa-search"></i> Buscar</button>
    </div>
</form>

{% if movements %}
	<div class="row table-responsive" style="height: 500px;">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class="min-80" scope="col">Fecha</th>
					<th class="min-100 text-left" scope="col">Clasificación</th>
					<th class="min-80 text-right" scope="col">COD invitado</th>
					<th class="min-100 text-left" scope="col">Valor bonificación</th>
					{% comment %} <th class="min-100 text-left" scope="col">Tiempo de suscripción</th> {% endcomment %}
					<th class="min-100 text-left" scope="col">Fecha vencimiento</th>
				</tr>
			</thead>
			<tbody>
				{% for movement in movements %}
				<tr>
					<td scope="row">{{movement.create_date|date:"Y-m-d H:i:s"}}</td>
					<td scope="row" class="text-left">{{movement.get_type_bonus_display}}</td>
					{% if movement.type_movement.id == 4 %}
						<td scope="row" class="text-left">{{movement.code_invitation_direct}}</td>
					{% else %}
						<td scope="row" class="text-left"></td>
					{% endif %}
					<td scope="row" class="text-left">$ {{movement.amount|intcomma}}</td>
					{% comment %} <td scope="row" class="text-left">{{movement.card_subscription.payday | date:'Y-m-d'}}</td> {% endcomment %}
					<td scope="row" class="text-left">{{movement.card_subscription.fecha_vencimiento | default_if_none:"" | date:'Y-m-d'}}</td>
				</tr>		
				{% endfor %}
			</tbody>
			<thead>
				<tr>
					<th colspan="3" class="text-right">Total</th>
					<th class="text-left">$ {{total_movements|intcomma}}</th>
					<th colspan="1" class="text-left"></th>
				</tr>
			</thead>	
		</table>
	</div>
	<div class="row">
		<div class="col-12">
		<nav>
			<ul class="pagination justify-content-center">
			{% if movements.has_previous %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page=1"><i class="fa fa-fast-backward"></i></a></li>
			{% endif %}
			{% if movements.has_previous %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.previous_page_number }}"><i class="fa fa-step-backward"></i></a></li>
			{% endif %}
			{% for i in movements.paginator.page_range %}
				{% if movements.number == i %}
				<li class="page-item active"><a  class="page-link" href="" disabled>{{ i }}</a></li>
				{% else %}
				<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ i }}" >{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if movements.has_next%}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.next_page_number }}"><i class="fa fa-step-forward"></i></a></li>
			{% endif %}
			{% if movements.has_next %}
			<li class="page-item"><a  class="page-link" href="?codigo_invitacion={{codigo_invitacion}}&page={{ movements.paginator.num_pages }}"><i class="fa fa-fast-forward"></i></a></li>
			{% endif %}
			</ul>
		</nav>
		</div>
	</div>
{% endif %}
  {% endblock %}

templates/guests/formulario.html
{% extends 'general/base.html' %}
{% block menu %}{% include "general/guest_menu.html" %}{% endblock%}
{% load static %}
{% block script %}
{% endblock %}
{% block container %}
{% if messages %}
	<div class="alert alert-success alert-dismissible fade show text-left" role="alert">
		<ul>
			{% for message in messages %} 
			<li><strong>{{message}}</strong></li>
			{% endfor %}
		</ul>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  		<span aria-hidden="true">&times;</span>
		</button>
  	</div>
{% endif %}
<form id="form" class="row mt-2" method="POST">
	{% csrf_token %}
	<div class="col-6">
		{{ form.invitation_code.label }}
        <div class="form-group">
            {{ form.invitation_code }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form.invitation_code.errors}}</div>
    </div>
	<div class="col-6">
		{{ form.amount.label }}
        <div class="form-group">
            {{ form.amount }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form.amount.errors}}</div>
    </div>
	<div class="col-12">
		<button type="submit" form="form" name="action" value="create" class="btn btn-sm btn-block btn-primary">Realizar recarga</button>
    </div>
</form>
{% endblock %}
{% block modal_title %}Realizar recarga{% endblock%}

templates/guests/formulario_transfer.html
{% extends 'general/base.html' %}
{% block menu %}{% include "general/guest_menu.html" %}{% endblock%}
{% load static %}
{% block script %}
{% endblock %}
{% block container %}
{% if messages %}
	<div class="alert alert-success alert-dismissible fade show text-left" role="alert">
		<ul>
			{% for message in messages %} 
			<li><strong>{{message}}</strong></li>
			{% endfor %}
		</ul>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  		<span aria-hidden="true">&times;</span>
		</button>
  	</div>
{% endif %}
<form id="form" class="row mt-2" method="POST">
	{% csrf_token %}
	<div class="col-6">
		{{ form.invitation_code_origin.label }}
        <div class="form-group">
            {{ form.invitation_code_origin }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form.invitation_code_origin.errors}}</div>
    </div>
	<div class="col-6">
		{{ form.invitation_code_destination.label }}
        <div class="form-group">
            {{ form.invitation_code_destination }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form.invitation_code_destination.errors}}</div>
    </div>
	<div class="col-12">
		{{ form.amount.label }}
        <div class="form-group">
            {{ form.amount }}
        </div>
		<div class="help-block with-errors text-danger" required>{{form.amount.errors}}</div>
    </div>
	<div class="col-12">
		<button type="submit" form="form" name="action" value="create" class="btn btn-sm btn-block btn-primary">Realizar transferencia</button>
    </div>
</form>
{% endblock %}
{% block modal_title %}Realizar recarga{% endblock%}