amarillos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.sitemaps.views import sitemap
from apps.users.views import login_user
admin.autodiscover()
admin.site.enable_nav_sidebar = False
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    # path('accounts/logout', logout_then_login, name="logout"),
    path(r'', login_user, name='login'),
    path('', include(('apps.users.urls', 'users'), namespace="users")),
    path('', include(('apps.taxes.urls', 'taxes'), namespace="taxes")),
    path('', include(('apps.regions.urls', 'regions'), namespace="regions")),
    path('', include(('apps.vehicles.urls', 'vehicles'), namespace="vehicles")),
    path('', include(('apps.services.urls', 'services'), namespace="services")),
    path('', include(('apps.guests.urls', 'guests'), namespace="guests")),
    #path('sitemap.xml',sitemap,{'sitemaps': sitemaps.sitemaps},name='django.contrib.sitemaps.views.sitemap',),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/guests/urls.py
from django.urls import path
from .views import *

app_name = "guests"

urlpatterns = [
    path('transfer',TransferView.as_view(),name='transfer'),
    path('recharge',RechargeView.as_view(),name='recharge'),
    path('balance',BalanceList.as_view(),name='balance'),
    path('bonus',BonusesList.as_view(),name='balance_bonus'),
] 

apps/regions/urls.py
from django.conf.urls import  include
from apps.regions.views import *
from django.urls import path
from django.contrib.auth.decorators import login_required

urlpatterns = [
	path(r'countries',login_required(countries), name='countries'),
	path(r'countries/<int:pk>',login_required(countries), name='countries'),
	path(r'departments',login_required(departments), name='departments'),
	path(r'departments/<int:pk>',login_required(departments), name='departments'),
	path(r'cities',login_required(cities), name='cities'),
	path(r'cities/<int:pk>',login_required(cities), name='cities'),
	path(r'locations_front', locations_front, name='locations_front'),
	path(r'locations_front/<int:pk>', locations_front, name='locations_front')
]

apps/taxes/urls.py
from django.conf.urls import  include
from apps.taxes.views import *
from django.urls import path
from django.contrib.auth.decorators import login_required
# èsto hace que saque horas aleatorias se deja por si a futuro toca implentarlo
# initial_benefits_policy()
urlpatterns = [
	path(r'membership',login_required(membership), name='membership'),
	path(r'agreement',login_required(agreement), name='agreement'),
	path(r'collections',login_required(collections), name='collections'),
	path(r'collections/<int:pk>',login_required(collections), name='collections'),
	path(r'time_zone',login_required(time_zone), name='time_zone'),
	path(r'time_zone/<int:pk>',login_required(time_zone), name='time_zone'),
	path(r'rate',login_required(rate), name='rate')
	# path(r'units_range',login_required(units_range), name='units_range'),
]

apps/users/urls.py
from django.conf.urls import  include
from apps.users.views import *
from apps.users.apiViews import *
from django.urls import path
from django.contrib.auth.decorators import login_required
urlpatterns = [
	path(r'index',login_required(index), name='index'),
	path(r'subscription', subscription, name='subscription'),
	path(r'invoices/', invoices, name='invoices'),
	path(r'invoice/<int:pk>', invoice, name='invoice'),

	path(r'registration', registration, name='registration'),
	# path(r'affiliate-registration/<str:code>',affiliate_registration, name='affiliate-registration'),
	path(r'registration_two',login_required(registration_two), name='registration_two'),

	path(r'categories',login_required(categories), name='categories'),
	path(r'categories/<int:pk>',login_required(categories), name='categories'),
    
	path(r'subscription2',login_required(subscription2), name='subscription2'),
	path(r'subscription2/<int:pk>',login_required(subscription2), name='subscription2'),

	path(r'coupons',login_required(coupons), name='coupons'),
	path(r'coupons/<int:pk>',login_required(coupons), name='coupons'),
	
	path(r'users',login_required(users), name='users'),
	path(r'users/<int:pk>',login_required(users), name='users'),

	path(r'operational_users',login_required(operational_users), name='operational_users'),
	path(r'operational_users/<int:pk>',login_required(operational_users), name='operational_users'),
	
	path(r'print_cards',login_required(print_cards), name='print_cards'),
	path(r'print_cards/<int:pk>',login_required(print_cards), name='print_cards'),
 
 	path(r'allys',login_required(allys), name='allys'),
	path(r'allys/<int:pk>',login_required(allys), name='allys'),
 	path(r'allys_two',login_required(allys_two), name='allys_two'),

	path(r'activate-card',login_required(activate_card), name='activate-card'),
	#api codigos
	path(r'api_cod/<str:cod>', api_cod, name='api_cod'),
	path(r'api_events_wompi', api_events_wompi, name='api_events_wompi'),
	path(r'login/', login_user, name='login'),
 	
    path(r'logout/', logout_user, name='logout'),
    path(r'password_recovery/', password_recovery, name='password_recovery'),
    path(r'password_reset/<uidb64>/<token>/', password_reset, name='password_reset'),
    path(r'profile_front', profile_front, name='profile_front'),

    path(r'activate_cards', activate_cards, name='activate_cards'),
    path(r'activate_card/<int:pk>', activate_card, name='activate_card'),
]

templates/general/base.html
<!DOCTYPE html>
<html class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% load static %}
        <title>Amarillos De Oro</title>

        <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static '/bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static '/sweetalert2/sweetalert2.min.css' %}">
        <link rel="stylesheet" href="{% static '/css/main.css' %}" />
        
        <!-- Font Awesome CSS -->
        <link rel="stylesheet" href="{% static '/fonts/css/font-awesome.css' %}">
        <link rel="shortcut icon" type="text/css" href="{% static '/image/LOGO_ADO.ico' %}" />
    </head>
    <body class="small">
        {% include "general/nav.html" %}
        <div class="container-fluid pr-5 pl-5"  style="background-color: #e5e5e5;">
            {% block menu %}{% endblock%}
        </div>
        <div class="container-fluid pr-5 pl-5" style="height: 68%;">
            {% block container %}{% endblock%}
        </div>
        <div class="modal fade" id="GeneralModal" tabindex="-1" role="dialog" aria-labelledby="GeneralModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered {% block modal-large %}{% endblock %}" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">{% block modal_title %}{% endblock%}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% block modal_body %}{% endblock%}
                    </div>
                    <div class="modal-footer">
                        {% block modal_footer %}{% endblock%}
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="GeneralModalImage" tabindex="-1" role="dialog" aria-labelledby="GeneralModalImage" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-center">
                        <img src="" width="100%%" class="img-fluid"></img>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="{% static '/jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/jquery/jquery-ui.min.js' %}"></script>
        <!-- Popper.JS <label class="font-weight-bold text-Csecondary h4">Ofertas que no puedes perderte</label>-->    
        <!-- Bootstrap JS  con popper.js-->
        <script type="text/javascript" src="{% static '/bootstrap/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/sweetalert2/sweetalert2.min.js' %}"></script>
        <script type="text/javascript" src="{% static '/apps/general/general.js' %}"></script>
        <!--Funcionalidades personalizadas generales-->
        {% block script %}{% endblock %}
    </body>
</html>

templates/general/base_front.html
{% load humanize %}
<!DOCTYPE html>
<html class="h-100">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		{% load static %}
		<title>Amarillos de oro</title>

		<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}">
		<link rel="stylesheet" href="{% static 'css/custom.css' %}" />
	</head>
	<body class="h-100 d-flex align-items-start flex-column {% block header_color %} {% endblock%}">
		<div class="container-fluid">	
		{% block header %}
			{% include "general/nav_front.html" with hide_subscription="true" hide_card="true" %}
		{% endblock%}
		</div>
		<div class="container-fluid mb-auto">
		{% block container %}

		{% endblock%}
		</div>
		<div class="container-fluid align-self-end {% block footer_color %}  {% endblock%}">
		{% block footer %}

		{% endblock%}
		</div>
		<script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'apps/general/general.js' %}"></script>
		<script type="text/javascript" src="{% static 'apps/general/config.js' %}?V=2"></script>
		{% block script %}

		{% endblock%}
		<script type="text/javascript">
				$(".js-dropdown_login").on("click", function(){
					$('[aria-labelledby="navbarDropdownLogin"]').toggleClass('show');
				});
		</script>
	</body>
</html>

templates/general/base_login.html
<!DOCTYPE html>
<html class="h-100">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		{% load static %}
		<title>Amarillos de oro</title>

		<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/custom.css' %}" />
	</head>
	<body class="h-100 d-flex align-items-start flex-column bg-Cprimary">
		{% block container %}

		{% endblock%}
		<script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
		{% block script %}

		{% endblock%}
	</body>
</html>

templates/general/general_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			{% if request.user.groups.all.0.id == 4 %}
			<!-- <a class="py-2 mr-5 text-secondary font-weight-bold {{active_users}}" href="{% url 'users:users' %}">Usuarios</a> -->
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_publications}}" href="{% url 'services:publications' %}">Publicaciones</a>
			<!-- <a class="py-2 mr-5 text-secondary font-weight-bold {{active_coupons}}" href="{% url 'services:pqr' %}">PQRs</a> -->
			{% endif %}
			{% if request.user.groups.all.0.id == 6 %}
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_registration_two}}" href="{% url 'users:registration_two' %}">Completar registro</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_registration_vehicles}}" href="{% url 'vehicles:registration_vehicles' %}">Registrar o editar vehiculos</a>
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_registration_allys}}" href="{% url 'users:allys_two' %}">Registrar o editar aliados</a>
			{% endif %}

		</div>
	</div>
</div>

templates/general/guest_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_balance}}" href="{% url 'guests:balance' %}">Balance usuario</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_recharge}}" href="{% url 'guests:recharge' %}">Recargas</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_transfer}}" href="{% url 'guests:transfer' %}">Transferencia</a>
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_bonus}}" href="{% url 'guests:balance_bonus' %}">Bonificaciones</a>
		</div>
	</div>
</div>

templates/general/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" id="main-navbar">
    <a class="navbar-brand pr-5" href="{% url 'users:index' %}">
        <img src="{% static 'image/ado_logo_s.png' %}" height="45" class="d-inline-block align-top"/>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if request.user.groups.all.0.id == 4 %}
            <li class="nav-item nav-icon">
                <a href="{% url 'users:categories' %}">
                    <i class="fa fa-book"></i>
                    Tarifas
                </a>
            </li>
            {% endif %}
            {% if request.user.groups.all.0.id == 4 %}
            <li class="nav-item nav-icon">
                <a href="{% url 'services:publications' %}">
                    <i class="fa fa-cogs"></i>
                    General
                </a>
            </li>
            {% endif %}
            {% if request.user.groups.all.0.id == 4 or request.user.groups.all.0.id == 7 %}
            <li class="nav-item nav-icon">
                <a href="{% url 'services:service' %}">
                    <i class="fa fa-car"></i>
                    Servicios
                </a>
            </li>
            {% endif %}
            {% if request.user.groups.all.0.id == 4 %}
            <li class="nav-item nav-icon">
                <a href="{% url 'users:operational_users' %}">
                    <i class="fa fa-users"></i>
                    Usuarios
                </a>
            </li>
            <li class="nav-item nav-icon">
                <a href="{% url 'guests:balance' %}">
                    <i class="fa fa-handshake-o"></i>
                    Plan de compensación
                </a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav mr-3 align-items-left">
            <li class="nav-item nav-icon">
                <img src="{% if request.user.extended_user.photo %}request.user.extended_user.photo.url{% else %}{% static 'image/defaultProfile.jpg' %}{% endif %}" height="35" class="d-inline-block align-top rounded-circle" style="vertical-align:middle !important"/> 
                <span class="d-none d-md-inline">{{request.user.username}}</span>
            </li>
            <li class="nav-item nav-icon">
                <a href="{% url 'users:logout' %}" title="Cerrar sesion">
                    <i class="fa fa-sign-out align-middle"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

templates/general/nav_front.html
{% load static %}
<div class="row my-2">
	<div class="col-2 d-flex align-items-center justify-content-center">
		<i class="fa fa-times fa-2x text-Csecondary pointer-C" data-toggle="modal" data-target="#modal_logout_nav"></i>
	</div>
    
	<div class="col-2 offset-8 d-flex align-items-center justify-content-center">
        <i class="fa fa-bars fa-2x text-Csecondary js-dropdown_login pointer-C" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></i>
	</div>
</div>
<div class="collapse position-absolute bg-white border border-Csecondary rounded-C5 collapse-CNav" id="collapseExample">
    <div class="container-fluid">
    {% if hide_service_associate != 'true' and request.user.groups.all.0.id == 2 %}   
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'services:service_front_associate' %}">
                <i class="fa fa-hashtag pr-2"></i>
                <span>Cod. servicio</span>
            </a>
        </div>
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'vehicles:vehicles_front' %}">
                <i class="fa fa-taxi pr-2"></i>
                <span>Vehículos</span>
            </a>
        </div>
    {% endif%}
    {% if hide_service != 'true' %}   
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'services:service_front_affiliate' %}">
                <i class="fa fa-plus pr-2"></i>
                <span>ado</span>
            </a>
        </div>
    {% endif%}
    {% if hide_locations != 'true' %}   
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'regions:locations_front' %}">
                <i class="fa fa-map-marker pr-2"></i>
                <span>Destinos</span>
            </a>
        </div>
    {% endif%}
    {% if hide_pqrs != 'true' %} 
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'services:pqr_front' %}">
                <i class="fa fa-list-alt pr-2"></i>
                <span>PQRs</span>
            </a>
        </div>
    {% endif%}
    {% if hide_history != 'true' %}
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'services:travel_history' %}">
                <i class="fa fa-hourglass pr-2"></i>
                <span>Historial de viajes</span>
            </a>
        </div>
    {% endif%}
    {% if hide_invoice != 'true' %}
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'users:invoices' %}">
                <i class="fa fa-hourglass pr-2"></i>
                <span>Factura</span>
            </a>
        </div>
    {% endif%}
    {% if hide_card != 'true' %}
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'users:activate_cards' %}">
                <i class="fa fa-hourglass pr-2"></i>
                <span>Activación</span>
            </a>
        </div>
    {% endif%}
    {% if hide_subscription != 'true' %}
        <div class="row mx-0 my-2 pointer-C">
            <a class="text-secondary font-weight-bold" href="{% url 'users:subscription' %}">
                <i class="fa fa-hourglass pr-2"></i>
                <span>Pagar suscripción</span>
            </a>
        </div>
    {% endif%}
    </div>
</div>
<div class="row text-center">
	<div class="col-4 offset-4 col-md-2 offset-md-5">
		<img src="{% static 'image/ado_logo_s.png' %}" class="img-fluid">
	</div>
</div>
<div class="modal fade" id="modal_logout_nav" tabindex="-1" role="dialog" aria-labelledby="modal_logout_nav" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cerrar sesión</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <i class="fa fa-sign-out align-middle"></i>
                </button>
            </div>
            <div class="modal-body">
                ¿ Deseas cerrar sesión ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm mt-1 bg-Csecondary btn-block text-white" data-dismiss="modal">Cancelar</button>
                <a href="{% url 'users:logout' %}" role="button" class="btn btn-sm btn-block bg-Cprimary text-Csecondary">Aceptar</a>
            </div>
        </div>
    </div>
</div>

templates/general/region_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			<!-- <a class="py-2 mr-5 text-secondary font-weight-bold {{active_countries}}" href="{% url 'regions:countries' %}">Paises</a> -->
			<a class="py-2 mr-5 text-secondary font-weight-bold {{active_departments}}" href="{% url 'regions:departments' %}">Departamentos</a>
			<a class="py-2 mr-5 text-secondary font-weight-bold {{active_cities}}" href="{% url 'regions:cities' %}">Ciudades</a>
		</div>
	</div>
</div>  

templates/general/service_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			{% comment %} <a class="py-2 mr-5 text-secondary font-weight-bold {{active_service}}" href="{% url 'services:service' %}">{% if request.user.groups.all.0.id == 7 %}Control de calidad{% else %}Historial de viajes{% endif %}</a> {% endcomment %}
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_service}}" href="{% url 'services:service' %}">Control de calidad</a>
			{% if not request.user.groups.all.0.id == 7 %}
				<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_travel_history}}" href="{% url 'services:travel_history_back' %}">Historial de viajes</a>
			{% endif %}
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_pqr}}" href="{% url 'services:pqr' %}">PQRs</a>
		</div>
	</div>
</div>

templates/general/taxe_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 py-2 pr-2 text-secondary font-weight-bold {{active_categories}}" href="{% url 'users:categories' %}">Categorias</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 py-2 pr-2 text-secondary font-weight-bold {{active_time_zone}}" href="{% url 'taxes:time_zone' %}">Franjas Horarias</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 py-2 pr-2 text-secondary font-weight-bold {{active_rate}}" href="{% url 'taxes:rate' %}">Tarifas de ley</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 py-2 pr-2 text-secondary font-weight-bold {{active_collections}}" href="{% url 'taxes:collections' %}">Recargos de Ley</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 py-2 pr-2 text-secondary font-weight-bold {{active_print_cards}}" href="{% url 'users:subscription2' %}">Suscripciones</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_coupons}}" href="{% url 'users:coupons' %}">Cupones de regalo</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_departments}}" href="{% url 'regions:departments' %}">Departamentos</a>
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_cities}}" href="{% url 'regions:cities' %}">Ciudades</a>
		</div>
	</div>
</div>  

templates/general/user_menu.html
{% load static %}
<div class="col col-md-12 border-bottom">
	<div class="row py-2">
		<div class="col offset-1 d-flex flex-wrap stepLabel_bottomline">
			{% if request.user.groups.all.0.id == 4 %}
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_operational_users}}" href="{% url 'users:operational_users' %}">Operativos</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_print_cards}}" href="{% url 'users:print_cards' %}">Usuarios</a>
			<a style="border-left: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_allys}}" href="{% url 'users:allys' %}">Aliados</a>
			<a style="border-left: 2px #c0c0c0 solid;border-right: 2px #c0c0c0 solid;" class="pl-2 pr-2 py-2 text-secondary font-weight-bold {{active_vehicles}}" href="{% url 'vehicles:vehicles_list' %}">Vehículos</a>
			
			{% endif %}
		</div>
	</div>
</div>