amarillos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.sitemaps.views import sitemap
from apps.users.views import login_user
admin.autodiscover()
admin.site.enable_nav_sidebar = False
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/login/', LoginView.as_view(template_name="users/login.html"), name="login"),
    # path('accounts/logout', logout_then_login, name="logout"),
    path(r'', login_user, name='login'),
    path('', include(('apps.users.urls', 'users'), namespace="users")),
    path('', include(('apps.taxes.urls', 'taxes'), namespace="taxes")),
    path('', include(('apps.regions.urls', 'regions'), namespace="regions")),
    path('', include(('apps.vehicles.urls', 'vehicles'), namespace="vehicles")),
    path('', include(('apps.services.urls', 'services'), namespace="services")),
    path('', include(('apps.guests.urls', 'guests'), namespace="guests")),
    #path('sitemap.xml',sitemap,{'sitemaps': sitemaps.sitemaps},name='django.contrib.sitemaps.views.sitemap',),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.conf.urls import  include
from apps.users.views import *
from apps.users.apiViews import *
from django.urls import path
from django.contrib.auth.decorators import login_required
urlpatterns = [
	path(r'index',login_required(index), name='index'),
	path(r'subscription', subscription, name='subscription'),
	path(r'invoices/', invoices, name='invoices'),
	path(r'invoice/<int:pk>', invoice, name='invoice'),

	path(r'registration', registration, name='registration'),
	# path(r'affiliate-registration/<str:code>',affiliate_registration, name='affiliate-registration'),
	path(r'registration_two',login_required(registration_two), name='registration_two'),

	path(r'categories',login_required(categories), name='categories'),
	path(r'categories/<int:pk>',login_required(categories), name='categories'),
    
	path(r'subscription2',login_required(subscription2), name='subscription2'),
	path(r'subscription2/<int:pk>',login_required(subscription2), name='subscription2'),

	path(r'coupons',login_required(coupons), name='coupons'),
	path(r'coupons/<int:pk>',login_required(coupons), name='coupons'),
	
	path(r'users',login_required(users), name='users'),
	path(r'users/<int:pk>',login_required(users), name='users'),

	path(r'operational_users',login_required(operational_users), name='operational_users'),
	path(r'operational_users/<int:pk>',login_required(operational_users), name='operational_users'),
	
	path(r'print_cards',login_required(print_cards), name='print_cards'),
	path(r'print_cards/<int:pk>',login_required(print_cards), name='print_cards'),
 
 	path(r'allys',login_required(allys), name='allys'),
	path(r'allys/<int:pk>',login_required(allys), name='allys'),
 	path(r'allys_two',login_required(allys_two), name='allys_two'),

	path(r'activate-card',login_required(activate_card), name='activate-card'),
	#api codigos
	path(r'api_cod/<str:cod>', api_cod, name='api_cod'),
	path(r'api_events_wompi', api_events_wompi, name='api_events_wompi'),
	path(r'login/', login_user, name='login'),
 	
    path(r'logout/', logout_user, name='logout'),
    path(r'password_recovery/', password_recovery, name='password_recovery'),
    path(r'password_reset/<uidb64>/<token>/', password_reset, name='password_reset'),
    path(r'profile_front', profile_front, name='profile_front'),

    path(r'activate_cards', activate_cards, name='activate_cards'),
    path(r'activate_card/<int:pk>', activate_card, name='activate_card'),
]

apps/users/views.py
from apps.guests.models import balance_wallet, wallet
import collections
from apps.users.models import *
from apps.regions.models import *
from apps.users.forms import *
from apps.users.externalApis import *
from django.http import HttpResponse
# django tools
import datetime
import pytz
from apps.users.resources import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.shortcuts import get_object_or_404, render,redirect
from django.db.models import Q, F, Subquery, OuterRef, ExpressionWrapper, DateField, DateTimeField, DurationField
from django.db.models.functions import TruncDate
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import get_template

def login_user(request):
	context={}
	if request.user.is_authenticated:
		user = request.user
		if user.groups.filter(id=6).exists():
			return redirect('users:registration_two')
		elif user.groups.filter(id=4).exists() or user.groups.filter(id=7).exists():
			return redirect('users:index')
		else:
			today = timezone.now()
			card_subscription = CardSubscription.objects.filter(card__user_id=request.user.id, invoice__state_id=2).annotate(date_expiry= ExpressionWrapper(F('payday') + ExpressionWrapper(F('subscription__type_subscription__days')* 24 * 60 * 60 * 1000000, output_field=DurationField()), output_field=DateTimeField()))
			card_subscription = card_subscription.filter(date_expiry__gte = today)
			if card_subscription.filter(state_id=1).exists() and (user.groups.filter(id=1).exists() or user.groups.filter(id=5).exists()):
				request.session['user_activate'] = 'active_user'
				return redirect('services:service_front_affiliate')
			elif card_subscription.filter(state_id=1).exists() and user.groups.filter(id=2).exists():
				request.session['user_activate'] = 'active_user'
				return redirect('services:service_front_associate')
			elif card_subscription.filter(state_id=2).exists():
				request.session['user_activate'] = 'activate_card'
				return redirect('users:activate_card', pk=card_subscription.filter(state_id=2)[0].id)
			else:
				request.session['user_activate'] = 'subscription'
				return redirect('users:subscription')	
	if request.GET.get('register') != None:
		context['message'] = "Registro exitoso, puedes ingresar a la plataforma con las credenciales creadas"
	if request.POST:
		form=AuthenticationForm(None, request.POST)
		username = request.POST['username']
		password = request.POST['password']
		if form.is_valid():
			user = authenticate(username=username, password=password)
			if user is not None:
				obj_extended_user = Extended_User.objects.filter(pk=user.pk).first() or None
				if obj_extended_user:
					date_now = datetime.datetime.now()
					if obj_extended_user.inactive_until:
						fecha = obj_extended_user.inactive_until
						utc = fecha.replace(tzinfo=pytz.UTC)
						fecha = utc.astimezone(timezone.get_current_timezone())
						utc = date_now.replace(tzinfo=pytz.UTC)
						date_now = utc.astimezone(timezone.get_current_timezone())
						if fecha >= date_now: 
							form.add_error(None, "Usuario inactivo hasta la fecha "+str(fecha.strftime("%Y-%m-%d %H:%M")))
							context['form']=form 
							return render(request, "users/login_front.html", context)
				login(request, user)
				if user.groups.filter(id=6).exists():
					return redirect('users:registration_two')
				elif user.groups.filter(id=4).exists() or user.groups.filter(id=7).exists():
					return redirect('users:index')
				else:
					today = timezone.now()
					card_subscription = CardSubscription.objects.filter(card__user_id=request.user.id, invoice__state_id=2).annotate(date_expiry= ExpressionWrapper(F('payday') + ExpressionWrapper(F('subscription__type_subscription__days')* 24 * 60 * 60 * 1000000, output_field=DurationField()), output_field=DateTimeField()))
					card_subscription = card_subscription.filter(date_expiry__gte = today)
					if card_subscription.filter(state_id=1).exists() and (user.groups.filter(id=1).exists() or user.groups.filter(id=5).exists()):
						request.session['user_activate'] = 'active_user'
						return redirect('services:service_front_affiliate')
					elif card_subscription.filter(state_id=1).exists() and user.groups.filter(id=2).exists():
						request.session['user_activate'] = 'active_user'
						return redirect('services:service_front_associate')
					elif card_subscription.filter(state_id=2).exists():
						request.session['user_activate'] = 'activate_card'
						return redirect('users:activate_card', pk=card_subscription.filter(state_id=2)[0].id)
					else:
						request.session['user_activate'] = 'subscription'
						return redirect('users:subscription')	
			else:
				form.add_error(None, "Usuario no encontrado")
		context['form']=form
	return render(request, "users/login_front.html", context)

def password_recovery(request):
	context={}
	if request.POST:
		form=PasswordResetForm(request.POST)
		if form.is_valid():
			# form.save()
			plaintext = get_template('users/email_recovery.txt')
			template_html= get_template('users/email_recovery.html')
			user= User.objects.filter(email=request.POST['email'].lower())[0]
			context = {
                'domain': "http://82.180.137.125:8021",
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': default_token_generator.make_token(user),
            }

			subject, from_email, to, cc = '¡ '+"Restaurar contraseña"+' !', 'ado@tarjetaxi.com', [user.email], ['pedro.balcazar@gmail.com']
			text_content = plaintext.render(context)
			html_content = template_html.render(context)
			msg = EmailMultiAlternatives(subject, text_content, from_email, to, cc=cc)
			msg.attach_alternative(html_content, "text/html")
			msg.send()
			messages.error(request, 'Se envio un correo siga las instrucciones para restaurar la contraseña.')
			return redirect('users:login')
		else:
			print(form.errors)
		context['form']=form
	return render(request, "users/password_recovery.html", context)	

def password_reset(request, uidb64, token):
	context={}
	uid = urlsafe_base64_decode(uidb64).decode()
	user = User.objects.get(pk=uid)
	if token == 'set_password':
		session_token = request.session.get('_password_reset_token')
		if default_token_generator.check_token(user, session_token) and request.POST:
			form=SetPasswordForm(user, request.POST)
			if form.is_valid():
				form.save()
				messages.error(request, 'El cambio de contraseña fue exitoso.')
				return redirect('users:login')
			else:
				print(form.errors)
			context['form']=form
	else:
		if default_token_generator.check_token(user, token):
			request.session['_password_reset_token'] = token
			redirect_url = request.path.replace(token, 'set_password')
			return HttpResponseRedirect(redirect_url)
	return render(request, "users/password_reset.html", context)

def logout_user(request):
    logout(request)
    return redirect('users:login')

# La vista de inicio.
def index(request):
	return render (request,"users/index.html")

def subscription(request):
	obj_extended_user = get_object_or_404(Extended_User,user=request.user)
	if obj_extended_user.photo is None or obj_extended_user.photo == "":
		messages.error(request, 'Debe de dirigirse primero a un punto de registro para complementear la información')
		return redirect('users:logout')
	subscription=Subscription.objects.filter(group_id= request.user.groups.all()[0].id)
	context={
		"subscription": subscription,
	}
	invoice= Invoice.objects.filter(user_id=request.user.id, state=1)
	if invoice.exists():
		invoice=invoice[0]
	else:
		invoice= Invoice(user_id=request.user.id, state_id=1)
		invoice.save()
	card_subscription= CardSubscription.objects.filter(invoice_id=invoice.id)
	card= Card.objects.filter(user_id=request.user.id)
	if request.POST:
		invoice.payment_reference=str(invoice.id)+"-"+get_random_string(length=6)
		invoice.save()
		request.POST = request.POST.copy()
		request.POST.update({'invoice': invoice.id, 'card': card[0].id, 'state': 2})
		form = CardSubscriptionForm(request.POST, instance=card_subscription[0]) if card_subscription.exists() else CardSubscriptionForm(request.POST)
	
		if form.is_valid():
			card_save=form.save()
			if request.POST.get('coupon', None):
				coupon= Coupon.objects.filter(code=request.POST['coupon'], used= False, subscription_id= card_save.subscription.id, state_id= 1).first() or None
				if coupon:
					date_today = timezone.now()					
					if coupon.expiration_date is None or coupon.expiration_date > date_today:						
						invoice.payment_method = "CUPON"
						invoice.coupon_id = coupon.id
						invoice.total_price = card_save.subscription.price 
						invoice.state_id =  2
						invoice.save()
						coupon.used = True
						coupon.save()
						return redirect('users:invoice', pk=invoice.id )
					else:
						form.add_error(None, "El codigó ya expiro, fecha de expiración "+coupon.expiration_date.strftime("%Y-%m-%d"))
				else:
					form.add_error(None, "Codigó no valido o no disponible para este plan.")
			else:
				context['card_save'] = card_save
		else:
			print(form.errors)
	else:
		form = CardSubscriptionForm(instance=card_subscription[0]) if card_subscription.exists() else None
	context['form'] = form
	return render (request,"users/subscription.html", context)

def subscription2(request, pk=None):
	subscriptions=Subscription.objects.all().order_by('group_id')
	type_subscriptions=TypeSubscription.objects.all()

templates/users/categories.html
{% extends 'general/base.html' %}
{% block menu %}{% include "general/taxe_menu.html" %}{% endblock%}
{% block script %}
<script>
$('#GeneralModal').modal('{{modal}}');
$('#GeneralModal').on('hidden.bs.modal', function (e) {
	{% if category %}
	window.history.back();
	{% endif %}
});
</script>
{% endblock %}
{% block container %}
<div class="row d-flex justify-content-end">
	<a class="h6 text-success font-weight-bold" href="#" role="button" data-toggle="modal" data-target="#GeneralModal"><i class="fa fa-plus mr-2"></i>Nuevo</a>
	{# <button type="submit" form="createform" name="action" value="new" class="btn btn-sm btn-block btn-primary"> #}
		{# {% if city %}Editar {% else %}Crear{% endif %} #}
</div>
<div class="row">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Nombre</th>
				<th scope="col">Afectación por categoria %</th>
				<th scope="col">Opciones</th>
			</tr>
		</thead>
		<tbody>
			{% for x in categories %}
			<tr>
				<td scope="row">{{ x.id }}</td>
				<td scope="row">{{ x.name }}</td>
				<td scope="row">{{ x.discount }}</td>
				<td scope="row">
					<a class="fa fa-pencil-square-o text-Cprimary ml-2 cursor-pointer" href="{% url 'users:categories' x.id %}"></a>
					{#<a class="fa fa-trash text-danger ml-2 cursor-pointer js-delete" data-value="{{city.id}}" role="button" data-toggle="modal" data-target="#DeleteModal"></a>#}
				</td>
			</tr>		
			{% endfor %}
		</tbody>	
	</table>
</div>
{% endblock %}
{% block modal_title %}{% if category %}Editar {% else %}Crear{% endif %} categoria{% endblock%}
{% block modal_body %}
<form  method="POST" class="form-signin m-2" id="createform">
	{% csrf_token %}
	<div class="form-group row">
        <label for="name" class="col-3 col-form-label text-right">
          Nombre:
        </label>
        <div class="col-9">
          <input type="text"  class="form-control {% if form.name.errors %}border-bottom border-danger{% endif %}" name="name" id="name" placeholder="Nombre" value="{% if form.errors %}{{form.name.value}}{% else %}{{category.name}}{% endif %}">
        </div>
        {% if form.name.errors %}
          {{form.name.errors}}
        {% endif %}
  	</div>
  	<div class="form-group row">
        <label for="discount" class="col-3 col-form-label text-right">
          Afectación por categoria:
        </label>
        <div class="col-3">
          <input type="number"  class="form-control {% if form.discount.errors %}border-bottom border-danger{% endif %}" min="-100" max="100" name="discount" id="discount" placeholder="Porcentaje" value="{% if form.errors %}{{form.discount.value|floatformat:0}}{% else %}{{category.discount|floatformat:0}}{% endif %}">
        </div>
        {% if form.discount.errors %}
          {{form.discount.errors}}
        {% endif %}
	</div>
</form>
{% endblock%}
{% block modal_footer %}
<button type="button" class="btn btn-sm mt-1 btn-secondary btn-block" data-dismiss="modal">Cerrar</button>
<button type="submit" form="createform" name="action" value="create" class="btn btn-sm btn-block btn-primary">
	{% if category %}Editar {% else %}Crear{% endif %}
</button>
{% endblock%}

templates/users/login.html
{% extends "general/base_login.html" %}
{% load static %}
{% block container %}
<img src="{% static "image/LOGO_ADO.webp" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">
<form method="POST" action="{% url "users:login" %}" class="form-signin">
  {% csrf_token %}
  <input type="text" placeholder="Username" class="form-control" name="username" value="{% if form.errors %}{{form.username.value}}{% endif %}" />
  <input type="password" placeholder="Password" class="form-control mt-2" name="password" />
  <button type="submit" class="btn btn-lg btn-primary btn-block mt-2">Ingresar</button>
</form>
{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Error!</strong>{{form.errors}}
</div>
{% endif %}
<div class="">
  <a href="{% url "users:registration" %}">Registrate</a>
  <br>
  <a href="#" data-toggle="modal" data-target="#exampleModal">¿Olvidaste tu contraseña?</a>
</div>
{% if message %}
<div class="alert alert-info" role="alert">
  {{message}}
</div>
{% endif %}
{% endblock %}

templates/users/login_front.html
{% extends 'general/base_login.html' %}
{% load static %}
{% block script %}
<script type="text/javascript" src="{% static 'apps/users/login_front.js' %}"></script>
{% endblock%}
{% block container %}
<div class="container-fluid mb-auto">
	<div class="row mt-4 text-center">
		<div class="col-10 offset-1 col-md-2 offset-md-5">
			<img src="{% static 'image/ado_logo_s.png' %}" class="img-fluid">
		</div>
	</div>
	<!-- <div class="row text-center mt-2">	
		<div class="col-3">
				Afiliado
		</div>
		<div class="col-3 border-left border-secondary">Aliado</div>
		<div class="col-3 border-left border-secondary">Asociado</div>
		<div class="col-3 border-left border-secondary">PLus</div>
	</div> -->
	<div class="row my-4">
		<div class="col-10 offset-1 col-md-4 offset-md-4">
			<!-- <div class="row d-flex justify-content-center">
				¿Aún no has solicitado tu membresia?
			</div> -->
			<div class="row">
				<div class="col">
					<a href="{% url 'users:registration' %}" class="btn border-Csecondary form-control rounded-pill" role="button" aria-pressed="true">Suscríbete</a>
				</div>
			</div>
			<div class="row mt-4">
				<div class="col-4 offset-4">
					<img src="{% static 'image/membresia_icon.png' %}" class="img-fluid">
				</div>	
			</div>
		</div>
	</div>
	<div class="row my-4 text-center">
		<div class="col font-weight-bold">
			Iniciar sesión
		</div>
	</div>
	{% for err in form.non_field_errors %}
	<div class="col-10 offset-1">
		<div class="alert alert-danger alert-dismissible fade show">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{err}}
		</div>
	</div>
	{% endfor %}
	{% if success%}
	<div class="col-10 offset-1">
		<div class="alert alert-success alert-dismissible fade show">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{success}}
		</div>
	</div>
	{% endif %}
	{% if messages %}
		{% for message in messages %}
			<div class="col-10 offset-1">
				<div class="alert alert-success alert-dismissible fade show">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
						{{message}}
				</div>
			</div>
		{% endfor %}
	{% endif %}
	<form method="POST" class="row mb-4">
		{% csrf_token %}
		<div class="col-10 offset-1 col-md-4 offset-md-4">
			<div class="form-group text-center">
			    <label for="username">Ingresa tu correo</label>
			    <input type="text" id="username" name="username" class="form-control rounded-pill" placeholder="">
			    <div class="help-block with-errors text-danger">{{form.errors.username}}</div>
			</div>
			<div class="form-group text-center">
			    <label for="password">Ingresa tu contraseña</label>
			    <input type="password" id="password" name="password" class="form-control rounded-pill" placeholder="">
			    <div class="help-block with-errors text-danger">{{form.errors.password}}</div>
			</div>
			<div class="form-group form-check text-center mb-4">
			    <input type="checkbox" class="form-check-input" id="show_password">
			    <label class="form-check-label" for="show_password">Mostrar contraseña</label>
			</div>
		</div>
		<div class="col-6 offset-3 col-md-2 offset-md-5">
			<div class="form-group mt-4 text-center">
				<button type="submit" class="btn bg-Csecondary form-control rounded-pill text-Cprimary">Entrar</button>
			</div>
			<div class="text-center">
				<a href="{% url 'users:password_recovery' %}" class="text-dark" role="button" aria-pressed="true">¿Olvidaste la contraseña?</a>
			</div>
		</div>
		
	</form>
	
</div>
<div class="container-fluid bg-Csecondary align-self-end">
	<div class="row">
		<div class="col">
			<div class="row mt-3">
				<div class="col-2 offset-5">
					<img src="{% static 'image/ado_iso.png' %}" class="img-fluid">
				</div>
			</div>
			<div class="row text-center">
				<div class="col-12 text-white">
					Políticas de privacidad<br>
					Terminos y condiciones
				</div>
			</div>
			<div class="row mt-3">
				<div class="col px-0">
					<img src="{% static 'image/footer.png' %}" class="img-fluid">
				</div>
			</div>
		</div>
	</div>	
</div>
{% endblock%}

templates/users/subscription2.html
{% extends 'general/base.html' %}
{% load humanize %}
{% block menu %}{% include "general/taxe_menu.html" %}{% endblock%}
{% load static %}
{% block script %}
<script type="text/javascript" src="{% static 'apps/users/operational_users.js' %}"></script>
<script>
$('#GeneralModal').modal('{{modal}}');
$('#GeneralModal').on('hidden.bs.modal', function (e) {
	window.location.replace("/subscription2");
});
</script>
{% endblock %}
{% block container %}
<div class="row table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">Id</th>
				<th scope="col">Grupo</th>
				<th scope="col">Tipo de subscripción</th>
				<th scope="col">Descripción</th>
				<th scope="col">Precio</th>
				<th scope="col">Bonus directo</th>
				<th scope="col">Bonus indirecto</th>
				<th scope="col">Estado</th>
				<th scope="col">Opciones</th>
			</tr>
		</thead>
		<tbody>
			{% for x in subscriptions %}
			<tr>
				<td scope="row">{{x.id}}</td>
				<td scope="row">{{x.group}}</td>
				<td scope="row">{{x.type_subscription.name}}</td>
				<td scope="row">{{x.description}}</td>
				<td scope="row" class="text-right">$ {{x.price|floatformat:0|intcomma}}</td>
				<td scope="row" class="text-right">$ {{x.bonus_direct|floatformat:0|intcomma}}</td>
				<td scope="row" class="text-right">$ {{x.bonus_indirect|floatformat:0|intcomma}}</td>
				<td scope="row">{{x.state.name}}</td>
				<td scope="row">
					<a class="fa fa-pencil-square-o text-Cprimary ml-2 cursor-pointer" href="{% url 'users:subscription2' x.id %}"></a>
				</td>
			</tr>		
			{% endfor %}
		</tbody>	
	</table>
</div>
{% endblock %}
{% block modal_title %}{% if pk %}Editar {% else %}{% endif %}{% endblock%}
{% block modal_body %}
<form  method="POST" class="form-row form-signin m-2" id="createform">
	{% csrf_token %}
	<div class="form-group col-6 text-center">
		<label for="price">
			Precio:
    	</label>
    	<input type="text" class="form-control  min="0" {% if form.price.errors %}border-bottom border-danger{% endif %}" name="price" id="price" placeholder="$123" value="{{form.price.value|floatformat:0}}" pattern="^[0-9]+$">
    	<div class="help-block with-errors text-danger">{{form.price.errors}}</div>
	</div>
	<div class="form-group col-6 text-center">
		<label for="state">
			Estado:
		</label>
		<select class="form-control" id="state" name="state">
			<option>-----------</option>
    		{% for x in states %}
    		<option value="{{x.id}}" {% if form.state.value|floatformat:'0' == x.id|floatformat:'0' %} selected {% endif %} >{{x.name}}</option>
    		{% endfor %}
    	</select>
    	<div class="help-block with-errors text-danger">{{form.errors.state}}</div>
	</div>
	<div class="form-group col-6 text-center">
		<label for="bonus_direct">
			Precio:
    	</label>
    	<input type="text" class="form-control  min="0" {% if form.bonus_direct.errors %}border-bottom border-danger{% endif %}" name="bonus_direct" id="bonus_direct" placeholder="$123" value="{{form.bonus_direct.value|floatformat:0}}" pattern="^[0-9]+$">
    	<div class="help-block with-errors text-danger">{{form.bonus_direct.errors}}</div>
	</div>
	<div class="form-group col-6 text-center">
		<label for="bonus_indirect">
			Precio:
    	</label>
    	<input type="text" class="form-control  min="0" {% if form.bonus_indirect.errors %}border-bottom border-danger{% endif %}" name="bonus_indirect" id="bonus_indirect" placeholder="$123" value="{{form.bonus_indirect.value|floatformat:0}}" pattern="^[0-9]+$">
    	<div class="help-block with-errors text-danger">{{form.bonus_indirect.errors}}</div>
	</div>
	<div class="form-group col-12 text-center">
		<label for="description">
			Descripción:
		</label>
		<textarea class="form-control {% if form.description.errors %}}border-bottom border-danger{% endif %}" name="description" id="description" placeholder="Descripcion">{{ form.description.value }}</textarea>
		<div class="help-block with-errors text-danger" required>{{form.description.errors}}</div>
	</div>
	{% for err in form.non_field_errors %}
	<div class="col-10 offset-1">
		<div class="alert alert-danger alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{err}}
        </div>
	</div>
    {% endfor %}
</form>
{% endblock%}
{% block modal_footer %}
<div class="col-6">
	<button type="button" class="btn btn-sm btn-block btn-secondary" data-dismiss="modal">Cerrar</button>
</div>
<div class="col-6">
	<button type="submit" form="createform" class="btn btn-sm btn-block btn-primary">
		{% if pk %}Guardar{% else %}Guardar{% endif %}
	</button>	
</div>
{% endblock%}